//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : FormController.cs
//  @ Date : 2008-3-8
//  @ Author : 
//
//


public class FormController {
	public void InitForm(){
	}
}
